// <auto-generated />
namespace ZeroHunger.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class statusstring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(statusstring));
        
        string IMigrationMetadata.Id
        {
            get { return "202308010424258_statusstring"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
